import { useState, useEffect, useRef, useCallback } from 'react';
import { analyzeMeal, getStudents, getAgeGroup } from '../api';
import type { AnalysisResult, Student } from '../types';

type CaptureMode = 'camera' | 'upload' | null;
type IdMode = 'student_id' | 'age';

export default function ScanMeal() {
  const [students, setStudents] = useState<Student[]>([]);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);

  const [captureMode, setCaptureMode] = useState<CaptureMode>(null);
  const [idMode, setIdMode] = useState<IdMode>('student_id');
  const [studentId, setStudentId] = useState('');
  const [ageValue, setAgeValue] = useState<number>(12);

  const [uploadedImage, setUploadedImage] = useState<string | null>(null);

  const videoRef = useRef<HTMLVideoElement>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // What-if state
  const [dalQty, setDalQty] = useState(50);
  const oldScoreRef = useRef({ score: 68, status: 'review' });

  useEffect(() => {
    getStudents().then(s => {
      setStudents(s);
      if (s.length > 0) setStudentId(s[0].id);
    });
    // Stop camera on unmount
    return () => stopCamera();
  }, []);

  const stopCamera = () => {
    if (streamRef.current) {
      streamRef.current.getTracks().forEach(track => track.stop());
      streamRef.current = null;
    }
  };

  const startCamera = async () => {
    stopCamera();
    setCaptureMode('camera');
    setUploadedImage(null);
    setResult(null);
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: true });
      streamRef.current = stream;
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
      }
      
      // Speak the prompt and listen for response
      if ('speechSynthesis' in window) {
        const text = idMode === 'age' ? 'Tell me your age.' : 'Tell me your student ID.';
        const utterance = new SpeechSynthesisUtterance(text);
        
        utterance.onend = () => {
          const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
          if (SpeechRecognition) {
            const recognition = new SpeechRecognition();
            recognition.lang = 'en-US';
            recognition.interimResults = false;
            recognition.maxAlternatives = 1;
            
            recognition.onresult = (event: any) => {
              const transcript = event.results[0][0].transcript.trim().toLowerCase();
              console.log("Speech heard:", transcript);
              
              if (idMode === 'age') {
                const match = transcript.match(/\d+/);
                if (match) setAgeValue(parseInt(match[0], 10));
              } else {
                const match = transcript.match(/\d+/);
                if (match) {
                  const found = students.find(s => s.id.includes(match[0]));
                  if (found) setStudentId(found.id);
                }
              }
            };
            recognition.start();
          }
        };
        
        window.speechSynthesis.speak(utterance);
      }
    } catch (err) {
      console.error("Camera access denied or unavailable", err);
      alert("Camera access is required for this mode.");
      setCaptureMode(null);
    }
  };

  const handleUploadClick = () => {
    stopCamera();
    setCaptureMode('upload');
    setResult(null);
    fileInputRef.current?.click();
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (ev) => {
      setUploadedImage(ev.target?.result as string);
    };
    reader.readAsDataURL(file);
  };

  const captureFrame = (): string | null => {
    if (videoRef.current) {
      const canvas = document.createElement('canvas');
      canvas.width = videoRef.current.videoWidth;
      canvas.height = videoRef.current.videoHeight;
      const ctx = canvas.getContext('2d');
      if (ctx) {
        ctx.drawImage(videoRef.current, 0, 0, canvas.width, canvas.height);
        return canvas.toDataURL('image/jpeg', 0.8);
      }
    }
    return null;
  };

  const runAnalysis = async () => {
    if (idMode === 'student_id' && !studentId) {
      alert("Please select a student ID.");
      return;
    }
    
    setLoading(true);
    setResult(null);
    
    let imageData = undefined;
    if (captureMode === 'camera') {
      imageData = captureFrame() || undefined;
    } else if (captureMode === 'upload') {
      imageData = uploadedImage || undefined;
    }

    try {
      // If we are testing with mock backend, we use random quantities generated by backend.
      // We pass the appropriate identifiers.
      const r = await analyzeMeal({
        student_id: idMode === 'student_id' ? studentId : undefined,
        age: idMode === 'age' ? ageValue : undefined,
        meal_type: 'lunch',
        image_data: imageData
      });
      setResult(r);
      // Initialize dal quantity for what-if based on results
      setDalQty(r.quantities['dal'] || 50);
    } catch (e: any) { 
      console.error(e); 
      alert(e.message || "Failed to analyze meal.");
    } finally { 
      setLoading(false); 
    }
  };

  // What-if calculations
  const PROTEIN_TARGET = 18.0;
  const computeProtein = useCallback((dal: number) => 3.4 + dal * 0.183, []);
  const computeScore = useCallback((dal: number) => Math.max(0, Math.min(100, Math.round(68 + 0.4667 * (dal - 50)))), []);
  const statusFor = (score: number) => score >= 80 ? 'pass' : score >= 60 ? 'review' : 'fail';
  const labelFor = (s: string) => s === 'pass' ? 'Pass' : s === 'review' ? 'Review' : 'Fail';
  const colorFor = (s: string) => s === 'pass' ? { bg: '#DEE9DC', fg: '#2E5233', bar: '#4C7A4A' }
    : s === 'review' ? { bg: '#F2E2C0', fg: '#7A5A17', bar: '#C9922E' }
    : { bg: '#F1DAD4', fg: '#7A2A1C', bar: '#A03B2A' };

  const currentScore = computeScore(dalQty);
  const currentStatus = statusFor(currentScore);
  const currentProtein = computeProtein(dalQty);
  const currentCoverage = Math.min(100, Math.round((currentProtein / PROTEIN_TARGET) * 100));
  const c = colorFor(currentStatus);

  const student = students.find(s => s.id === studentId);
  const displayAge = idMode === 'student_id' ? (student?.age || '-') : ageValue;
  const displayAgeGroup = idMode === 'student_id' ? (student?.age_group || '-') : (ageValue < 9 ? '6-8' : ageValue < 11 ? '9-10' : ageValue < 15 ? '11-14' : '15-17');

  return (
    <div className="fade-in">
      <div className="page-head">
        <div>
          <h1>Scan meal</h1>
          <p className="sub">Capture a plate and verify nutrition instantly.</p>
        </div>
      </div>

      {/* ── Settings ──────── */}
      <div className="panel mb-5">
        <div className="section">
          <div className="flex gap-4 flex-wrap items-end">
            <div className="min-w-[180px]">
              <label className="text-[12px] text-[var(--color-ink-soft)] uppercase tracking-wider block mb-1">Identification Feature</label>
              <select value={idMode} onChange={e => setIdMode(e.target.value as IdMode)} className="input">
                <option value="student_id">Student ID (Registered Users)</option>
                <option value="age">Age Only (Anonymous)</option>
              </select>
            </div>
            
            {idMode === 'student_id' ? (
              <div className="flex-1 min-w-[180px]">
                <label className="text-[12px] text-[var(--color-ink-soft)] uppercase tracking-wider block mb-1">Select Student</label>
                <select value={studentId} onChange={e => setStudentId(e.target.value)} className="input">
                  <option value="" disabled>-- Select a Student --</option>
                  {students.map(s => <option key={s.id} value={s.id}>{s.id} — {s.name} (Age {s.age})</option>)}
                </select>
                {students.length === 0 && (
                  <p className="text-[11px] text-[var(--color-fail)] mt-1">No students registered yet. Go to Students tab.</p>
                )}
              </div>
            ) : (
              <div className="flex-1 min-w-[180px]">
                <label className="text-[12px] text-[var(--color-ink-soft)] uppercase tracking-wider block mb-1">Enter Age</label>
                <input type="number" min={5} max={18} value={ageValue} onChange={e => setAgeValue(Number(e.target.value))} className="input w-24" />
              </div>
            )}
          </div>
        </div>
      </div>

      {/* ── Capture Actions ──────── */}
      <div className="panel mb-5">
        <div className="section">
          <div className="flex gap-4">
            <button 
              onClick={startCamera} 
              className={`flex-1 p-6 border rounded-[3px] font-medium text-center transition-all cursor-pointer ${captureMode === 'camera' ? 'border-[var(--color-ink)] bg-[#F4F5F1]' : 'border-[var(--color-line)] bg-white hover:border-[var(--color-ink-soft)] hover:bg-[#FAFBF9]'}`}
            >
              <span className="block text-xl mb-2">📷</span>
              Use Camera
            </button>
            <button 
              onClick={handleUploadClick} 
              className={`flex-1 p-6 border rounded-[3px] font-medium text-center transition-all cursor-pointer ${captureMode === 'upload' ? 'border-[var(--color-ink)] bg-[#F4F5F1]' : 'border-[var(--color-line)] bg-white hover:border-[var(--color-ink-soft)] hover:bg-[#FAFBF9]'}`}
            >
              <span className="block text-xl mb-2">🖼️</span>
              Upload Picture
            </button>
          </div>
          <input ref={fileInputRef} type="file" accept="image/*" onChange={handleImageUpload} className="hidden" />
        </div>
      </div>

      {/* ── Capture View ──── */}
      {captureMode && (
        <div className="panel mb-5 fade-in">
          <div className="section text-center">
            {captureMode === 'camera' ? (
              <div className="bg-black inline-block rounded border border-[var(--color-line)] overflow-hidden w-full max-w-[640px] aspect-video">
                <video ref={videoRef} autoPlay playsInline muted className="w-full h-full object-cover" />
              </div>
            ) : (
              uploadedImage ? (
                <img src={uploadedImage} alt="Uploaded meal" className="max-w-[640px] w-full max-h-[360px] object-cover rounded-[3px] border border-[var(--color-line)] inline-block" />
              ) : (
                <div className="py-12 text-[var(--color-ink-soft)]">Please select an image file to upload.</div>
              )
            )}
            
            <div className="mt-6">
              <button onClick={runAnalysis} disabled={loading || (captureMode === 'upload' && !uploadedImage)} className="btn w-full max-w-sm h-12 text-base">
                {loading ? 'Analyzing AI...' : 'Analyze Meal'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── API result panel ──────── */}
      {result && (
        <div className="panel mt-5 fade-in scan-layout">
          <div>
            <div className="section">
              <h2 className="section-h">Analysis result — {result.status}</h2>
              <div className="flex items-baseline gap-3 mb-3">
                <span className="score-num" style={{ color: result.status === 'PASS' ? '#4C7A4A' : result.status === 'REVIEW' ? '#C9922E' : '#A03B2A' }}>
                  {Math.round(result.score)}
                </span>
                <span className="score-den">/ 100</span>
                <span className={`pill pill-${result.status.toLowerCase()} ml-auto`}>
                  {result.status === 'PASS' ? 'Pass' : result.status === 'REVIEW' ? 'Review' : 'Fail'}
                </span>
              </div>
            </div>

            <div className="section">
              <h2 className="section-h">Subject</h2>
              <div className="student-row"><span>ID / Mode</span><span>{idMode === 'student_id' ? result.student.id : 'Age-based (Anon)'}</span></div>
              <div className="student-row"><span>Age</span><span>{displayAge}</span></div>
              <div className="student-row"><span>Age group</span><span>{displayAgeGroup}</span></div>
            </div>

            <div className="section">
              <h2 className="section-h">Nutrient coverage</h2>
              {Object.entries(result.coverage).map(([key, cov]) => {
                const barColor = cov.adequate ? 'var(--color-veg)' : cov.coverage_pct >= 50 ? 'var(--color-dal)' : 'var(--color-fail)';
                return (
                  <div key={key} className="mb-2.5">
                    <div className="flex justify-between text-[12.5px] text-[var(--color-ink-soft)] mb-1">
                      <span className="capitalize">{key.replace(/_/g, ' ')}</span>
                      <span className="num">{cov.coverage_pct.toFixed(0)}%</span>
                    </div>
                    <div className="meter-track"><div className="meter-fill" style={{ width: `${Math.min(cov.coverage_pct, 100)}%`, background: barColor }} /></div>
                  </div>
                );
              })}
            </div>
            
            {result.recommendations.length > 0 && (
              <div className="section">
                <h2 className="section-h">Recommendations</h2>
                {result.recommendations.map((rec, i) => (
                  <div key={i} className="rec-card mb-3">
                    <div className="text-[11.5px] font-semibold text-[var(--color-dal)] mb-1">{rec.problem}</div>
                    <div className="text-[13.5px] text-[var(--color-ink-soft)]">{rec.suggestion}</div>
                  </div>
                ))}
              </div>
            )}
          </div>
          
          <div>
            <div className="section h-full flex flex-col">
              <h2 className="section-h">Detected plate</h2>
              <div className="tray flex-1 flex flex-col items-center justify-center p-6 border rounded mb-4">
                <div className="plate-wrap relative">
                  <svg viewBox="0 0 320 320" aria-hidden="true">
                    <circle cx="160" cy="160" r="150" fill="#F3F4EF" stroke="#D8DAD2" strokeWidth="1.5"/>
                    <path d="M 90 120 Q 60 170 95 220 Q 150 250 195 220 Q 175 150 140 115 Q 115 105 90 120 Z" fill="var(--color-rice)" stroke="#DCD2A6" strokeWidth="1"/>
                    <ellipse cx="220" cy="120" rx="46" ry="34" fill="var(--color-veg)" opacity="0.85"/>
                    <ellipse cx="150" cy="230" rx={40 + dalQty * 0.14} ry={26 + dalQty * 0.09} fill="var(--color-dal)" opacity="0.9" style={{ transition: 'all 0.3s ease' }} />
                  </svg>
                  <div className="plate-label" style={{ top: '16%', left: '14%' }}>Rice <span className="g">~{result.quantities['rice'] || 0} g</span></div>
                  <div className="plate-label" style={{ top: '12%', left: '62%' }}>Veg <span className="g">~{result.quantities['vegetable'] || 0} g</span></div>
                  <div className="plate-label" style={{ top: '68%', left: '38%' }}>Dal <span className="g">~{dalQty} g</span></div>
                </div>
              </div>

              {/* Render any other detected foods (like UNKNOWN FOOD) */}
              {Object.entries(result.quantities)
                .filter(([food]) => !['rice', 'dal', 'vegetable'].includes(food))
                .length > 0 && (
                <div className="mb-4 p-3 bg-[var(--color-fail-soft)] text-[var(--color-fail)] text-sm rounded border border-[var(--color-fail)]">
                  <strong>Other items detected:</strong>
                  <ul className="mt-1 ml-4 list-disc">
                    {Object.entries(result.quantities)
                      .filter(([food]) => !['rice', 'dal', 'vegetable'].includes(food))
                      .map(([food, qty]) => (
                        <li key={food}>{food}: ~{qty} g</li>
                      ))}
                  </ul>
                </div>
              )}
              
              <h2 className="section-h mt-4">What if — adjust dal quantity</h2>
              <div className="flex items-center gap-3.5 flex-wrap">
                <input type="range" min={20} max={150} step={5} value={dalQty}
                  onChange={e => setDalQty(Number(e.target.value))}
                  className="flex-1 min-w-[120px]" />
                <span className="num font-semibold min-w-[56px]">{dalQty} g</span>
                <button className="btn btn-secondary" onClick={() => setDalQty(result.quantities['dal'] || 50)}>Reset</button>
              </div>
              <p className="text-[12px] text-[var(--color-ink-soft)] mt-2 leading-relaxed">
                Move the slider to simulate adding or removing dal. Notice how the visual size changes instantly.
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function foodColor(food: string): string {
  const map: Record<string, string> = {
    rice: '#EFE8CC', dal: '#C9922E', vegetable: '#4C7A4A', roti: '#D4B896',
    egg: '#F5DEB3', salad: '#7CB342', potato: '#C9A96E', milk: '#E3E8ED',
  };
  return map[food] || '#D8DAD2';
}
